# Generated by Django 3.2.18 on 2023-04-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20230418_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='deathsummary',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='primary_consulting_doc',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='ipdpatient',
            name='ward',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='otschedule',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='otschedule',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='otschedule',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='patientdischarge',
            name='discharged_by',
        ),
        migrations.RemoveField(
            model_name='patientdischarge',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='DeathSummary',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='IPDPatient',
        ),
        migrations.DeleteModel(
            name='OTSchedule',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientDischarge',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
