# Generated by Django 3.2.18 on 2023-04-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_auto_20230418_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=255)),
                ('patient_history', models.TextField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
