# Generated by Django 3.2.18 on 2023-04-18 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
