# Generated by Django 4.2 on 2023-06-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
