# Generated by Django 4.2 on 2023-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='selected_test',
            field=models.CharField(max_length=255),
        ),
    ]
