# Generated by Django 4.1.5 on 2023-04-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scansummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpgfile', models.ImageField(upload_to='scans/')),
                ('scandetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekonapp.visit')),
            ],
        ),
    ]
