# Generated by Django 3.2.18 on 2023-04-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
