# Generated by Django 4.1.5 on 2023-04-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0002_scansummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekon',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
