# Generated by Django 4.2 on 2023-07-25 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekonapp', '0003_alter_visit_visit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
